# Generated by Django 4.2.4 on 2023-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя тура')),
                ('price', models.CharField(max_length=256, verbose_name='Цена тура')),
                ('photo', models.CharField(max_length=4096, verbose_name='Ссылка фото тура')),
                ('places_amount', models.CharField(max_length=256, verbose_name='Количество мест')),
                ('hotel_name', models.CharField(max_length=256, verbose_name='Имя отеля')),
                ('hotel_link', models.CharField(max_length=256, verbose_name='Ссылка к отелю')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
