# Generated by Django 4.2.4 on 2023-09-24 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Дата тура'),
            preserve_default=False,
        ),
    ]
