# Generated by Django 4.2.4 on 2023-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.CharField(max_length=128, verbose_name='Цена тура'),
        ),
    ]
