# Generated by Django 4.2.4 on 2023-09-16 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='tours-photos', verbose_name='Фото тура'),
            preserve_default=False,
        ),
    ]
