# Generated by Django 4.2.4 on 2023-09-20 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_name_tour_title_tour_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_link',
            field=models.CharField(default=1, max_length=256, verbose_name='Ссылка к отелю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Имя отеля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='places_amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Количество мест'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.CharField(max_length=256, verbose_name='Цена тура'),
        ),
    ]
