# Generated by Django 4.2.4 on 2023-09-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_rename_title_tour_name_tour_hotel_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.CharField(max_length=4096, verbose_name='Ссылка фото тура'),
        ),
    ]
