# Generated by Django 4.2.4 on 2023-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(max_length=256, verbose_name='Дата рождения')),
                ('country', models.CharField(max_length=256, verbose_name='Страна')),
                ('passport_data', models.CharField(max_length=256, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=256, verbose_name='Телефон номер')),
                ('tour_name', models.CharField(max_length=256, verbose_name='Имя тура')),
                ('tour_price', models.CharField(max_length=256, verbose_name='Цена тура')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
